services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
    env_file:
      - ./backend/.env

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: http backend:8000
    ports:
      - "4040:4040"  # ngrokのWebインターフェース（オプション）
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}  # .envファイルなどで定義
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host